### PR TITLE
normalized input of parseStringOrThrowError method

### LINKED ISSUE #594: `InputParser.parseStringOrThrowError` should additionally normalise the input
## 🐛 Bug Report

(A clear and concise description of what the bug is)

## Useful informations

(Write what happened. Add screenshots, stacktraces, videos, anything that can help)

### PR DESCRIPTION
**Pull request by Taz03**
## Related issues

fixes #594 

## Checklist for important updates

- [x] Changelog has been updated
    - [x] If there are any db schema changes, mention those changes clearly
- [x] `coreDriverInterfaceSupported.json` file has been updated (if needed)
- [x] `pluginInterfaceSupported.json` file has been updated (if needed)
- [x] Changes to the version if needed
    - In `build.gradle`
- [x] If added a new paid feature, edit the `getPaidFeatureStats` function in FeatureFlag.java file
- [x] Had installed and ran the pre-commit hook
- [x] If there are new dependencies that have been added in `build.gradle`, please make sure to add them
  in `implementationDependencies.json`.
- [x] Update function `getValidFields` in `io/supertokens/config/CoreConfig.java` if new aliases were added for any core config (similar to the `access_token_signing_key_update_interval` config alias).
- [x] Issue this PR against the latest non released version branch.
    - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the
      latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    - If no such branch exists, then create one from the latest released branch.
- [x] If added a foreign key constraint on `app_id_to_user_id` table, make sure to delete from this table when deleting the user as well if `deleteUserIdMappingToo` is false.

### CODE REVIEW

File: src/main/java/io/supertokens/webserver/InputParser.java [hunk 1]
```diff
@@ -137,7 +137,11 @@ public static String parseStringOrThrowError(JsonObject element, String fieldNam
             if (!stringified.contains("\"")) {
                 throw new Exception();
             }
-            return ((JsonObject) element).get(fieldName).getAsString();
+            String s = element.get(fieldName).getAsString().trim();
+            if (s.contains("@")) {
+                s = s.toLowerCase();
+            }
```
Comment (rishabhpoddar) [inline src/main/java/io/supertokens/webserver/InputParser.java:143]: We can't assume that if there is an `@`, it must be for an email input. Instead, we should use the full email regex to check, and if it passes that, only then we should do the toLowerCase.

File: src/main/java/io/supertokens/webserver/InputParser.java [hunk 2]
```diff
@@ -137,7 +137,11 @@ public static String parseStringOrThrowError(JsonObject element, String fieldNam
...
+            return s;
         } catch (Exception e) {
```
Comment (rishabhpoddar) [inline src/main/java/io/supertokens/webserver/InputParser.java:145]: Also, please add tests for this change please :)

**Review by rishabhpoddar — CHANGES_REQUESTED** [review]

File: src/main/java/io/supertokens/webserver/InputParser.java (hunk 2 above)
Comment (Taz03) [reply src/main/java/io/supertokens/webserver/InputParser.java:146]: Done

File: src/main/java/io/supertokens/webserver/InputParser.java (hunk 1 above)
Comment (Taz03) [reply src/main/java/io/supertokens/webserver/InputParser.java]: Done

File: src/main/java/io/supertokens/webserver/InputParser.java [hunk 3]
```diff
@@ -137,7 +137,12 @@ public static String parseStringOrThrowError(JsonObject element, String fieldNam
             if (!stringified.contains("\"")) {
                 throw new Exception();
             }
-            return ((JsonObject) element).get(fieldName).getAsString();
+            String s = element.get(fieldName).getAsString().trim();
+
+            if (s.matches("^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$")) {
```
Comment (rishabhpoddar) [inline src/main/java/io/supertokens/webserver/InputParser.java:142]: We use the following regex in our backend SDK: https://github.com/supertokens/supertokens-node/blob/master/lib/ts/recipe/emailpassword/utils.ts#L242. 

Might want to make this consistent with that.

**Review by rishabhpoddar — CHANGES_REQUESTED** [review]

File: src/main/java/io/supertokens/webserver/InputParser.java [hunk 4]
```diff
@@ -137,7 +137,12 @@ public static String parseStringOrThrowError(JsonObject element, String fieldNam
             if (!stringified.contains("\"")) {
                 throw new Exception();
             }
-            return ((JsonObject) element).get(fieldName).getAsString();
```
Comment (rishabhpoddar) [inline src/main/java/io/supertokens/webserver/InputParser.java:140]: This function is called for non GET request. We might want to add the trim and toLowerCase (in case of email), to the GET request equivalent as well. The functions are `getQueryParamOrThrowError` and `getCommaSeparatedStringArrayQueryParamOrThrowError`

**Review by rishabhpoddar — CHANGES_REQUESTED** [review]

File: src/main/java/io/supertokens/webserver/InputParser.java (hunk 4 above)
Comment (Taz03) [reply src/main/java/io/supertokens/webserver/InputParser.java:140]: do we want to trim in case of non-email in those methods as well?

File: src/main/java/io/supertokens/webserver/InputParser.java (hunk 3 above)
Comment (Taz03) [reply src/main/java/io/supertokens/webserver/InputParser.java]: Done

File: src/main/java/io/supertokens/webserver/InputParser.java (hunk 4 above)
Comment (Taz03) [reply src/main/java/io/supertokens/webserver/InputParser.java:140]: Done
